name: Price Trends

on:
  # push:
  #   branches: [main]
  schedule:
    - cron: "15 22 * * *" # Everyday at 22:15

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js.
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install dependencies.
        run: |
          cd scraper
          npm ci

      - uses: nick-invision/retry@v2
        with:
          timeout_seconds: 900 # 15 mins
          max_attempts: 8
          command: cd scraper && npm start

      - name: Copy price-trends.json.
        run: |
          cp scraper/price-trends.json /tmp/price-trends.json

      - name: change branch.
        run: |
          git fetch --all
          git checkout .
          git checkout price-trends-data
          cp /tmp/price-trends.json price-trends.json

      - uses: EndBug/add-and-commit@v5 # You can change this to use a specific version
        with:
          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: "🤖 Uploaded new price trends"
          author_name: Github Action
          author_email: i-am-a@robot.com
          branch: price-trends-data
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
